### ISSUE TITLE
Please update this repo

### ISSUE THREAD

**Issue by jimmydorry** [o0oradaro0o/Battleships_Reborn#2]
I can't make PRs unless it is up to date! The site is reporting that you are on v3, but this repo has v1.

**Comment by zentrx** [comment]
I'll get on that now. Gonna bug Radar and figure out what we want to do in that regard. Which site is reporting v3?

Edit: I totally misunderstood what you were talking about. He's fixing today.

**Comment by jimmydorry** [comment]
Thanks.
